language: node_js
node_js: 7
cache:
  directories:
    - "node_modules"
before_install:
  - npm i -g gatsby-cli
  - npm i -g npm@5.3.0
script:
  - gatsby build --prefix-paths
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: release